language: node_js
node_js:
  - "10"

script:
  - npm run eslint
  - npm run browser-build

deploy:
  local-dir: platforms/browser/www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
